name: Neworld Sign in

on:
  workflow_dispatch:
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print something
        run: env | pwd
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh & make code run
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: AKIA2JYANUWQNHQA5XWG
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/ubuntu/code
          command: ls -al
            
          
