name: Neworld Sign in

on:
  workflow_dispatch:
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print something
        run: env | pwd
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh & make code run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TG_HOST }}
          username: ${{ secrets.TG_USER }}
          password: ${{ secrets.TG_PASS }}
          script: |
            echo 'github action happened'
            
          