name: Neworld Sign in

on:
  workflow_dispatch:
    

jobs:
  ssm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: ssh & make code run
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/ubuntu/code
          command: ls -al
            
          
