name: Neworld Sign in

on:
  workflow_dispatch:
    

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: show enviroment
        run: env | grep ^GITHUB
      - name: show ref
        run: echo "vesion from $Github_REF"
